// <auto-generated />
using Kiemtragiuaki.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kiemtragiuaki.Migrations
{
    [DbContext(typeof(BoardingHouseContext))]
    partial class BoardingHouseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Kiemtragiuaki.Models.RoomImage_BIT240120", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsThumbnail")
                        .HasColumnType("bit");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("RoomImages_BIT240120", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "https://via.placeholder.com/300x200?text=Room+101",
                            IsThumbnail = true,
                            RoomId = 1
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "https://via.placeholder.com/300x200?text=Room+101+View",
                            IsThumbnail = false,
                            RoomId = 1
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "https://via.placeholder.com/300x200?text=Room+102",
                            IsThumbnail = true,
                            RoomId = 2
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "https://via.placeholder.com/300x200?text=Room+201",
                            IsThumbnail = true,
                            RoomId = 3
                        },
                        new
                        {
                            Id = 5,
                            ImageUrl = "https://via.placeholder.com/300x200?text=Room+202",
                            IsThumbnail = true,
                            RoomId = 4
                        },
                        new
                        {
                            Id = 6,
                            ImageUrl = "https://via.placeholder.com/300x200?text=Room+301",
                            IsThumbnail = true,
                            RoomId = 5
                        },
                        new
                        {
                            Id = 7,
                            ImageUrl = "https://via.placeholder.com/300x200?text=Room+302",
                            IsThumbnail = true,
                            RoomId = 6
                        });
                });

            modelBuilder.Entity("Kiemtragiuaki.Models.RoomType_BIT240120", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("RoomTypes_BIT240120", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A room designed for one person with basic amenities",
                            Name = "Single Room"
                        },
                        new
                        {
                            Id = 2,
                            Description = "A room designed for two people with enhanced comfort",
                            Name = "Double Room"
                        },
                        new
                        {
                            Id = 3,
                            Description = "A spacious room designed for families with multiple beds",
                            Name = "Family Room"
                        });
                });

            modelBuilder.Entity("Kiemtragiuaki.Models.Room_BIT24120", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Area")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("RoomTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoomTypeId");

                    b.HasIndex("Name", "RoomTypeId")
                        .IsUnique()
                        .HasDatabaseName("IX_Room_Name_RoomTypeId_Unique");

                    b.ToTable("Rooms_BIT240120", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Area = 25m,
                            Description = "Comfortable single room",
                            IsAvailable = true,
                            Name = "Room 101",
                            Price = 250000m,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Area = 30m,
                            Description = "Single room with balcony",
                            IsAvailable = true,
                            Name = "Room 102",
                            Price = 300000m,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 3,
                            Area = 40m,
                            Description = "Spacious double room",
                            IsAvailable = false,
                            Name = "Room 201",
                            Price = 450000m,
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 4,
                            Area = 45m,
                            Description = "Double room with city view",
                            IsAvailable = true,
                            Name = "Room 202",
                            Price = 500000m,
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 5,
                            Area = 60m,
                            Description = "Large family room",
                            IsAvailable = true,
                            Name = "Room 301",
                            Price = 750000m,
                            RoomTypeId = 3
                        },
                        new
                        {
                            Id = 6,
                            Area = 70m,
                            Description = "Luxurious family room",
                            IsAvailable = true,
                            Name = "Room 302",
                            Price = 800000m,
                            RoomTypeId = 3
                        });
                });

            modelBuilder.Entity("Kiemtragiuaki.Models.RoomImage_BIT240120", b =>
                {
                    b.HasOne("Kiemtragiuaki.Models.Room_BIT24120", "Room")
                        .WithMany("Images")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Kiemtragiuaki.Models.Room_BIT24120", b =>
                {
                    b.HasOne("Kiemtragiuaki.Models.RoomType_BIT240120", "RoomType")
                        .WithMany("Rooms")
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("Kiemtragiuaki.Models.RoomType_BIT240120", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("Kiemtragiuaki.Models.Room_BIT24120", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
